theme: jekyll-theme-tactile

plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - homeprojects/automated_door_gesture/Readme.md
  - LICENSE.md
  - COPYING.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - ISSUE_TEMPLATE.md
  - PULL_REQUEST_TEMPLATE.md
